import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/antd.registry";
import "./globals.css";
import AppHeader from "@/components/header/app-header";
import AppFooter from "@/components/footer/app-footer";
import { App } from "antd";
import Providers from "@/redux/Provider";


export const metadata: Metadata = {
  title: "BookWorm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <StyledComponentsRegistry>
          <Providers>
            <App>
              <AppHeader />
              {children}
              <AppFooter />
            </App>
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
