import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from '@/lib/antd.registry';
import "./globals.css"
import AppHeader from "@/components/header/app-header";
import AppFooter from "@/components/footer/app-footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Books",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <AppHeader />
          {children}
          <AppFooter />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
